version: '3.8'

services:

  #nginx
  server:
    image: 'nginx:stable-alpine'
    container_name: nginx_epsivent
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  #node
  npm:
    image: node:14
    container_name: node_cli

  #php
  php:
    build:
      context: docker-config
      dockerfile: php.dockerfile
    container_name: php_epsivent
    volumes:
      - ./:/var/www/html

  #composer
  composer:
    build:
      context: docker-config
      dockerfile: composer.dockerfile
    container_name: composer_cli
    volumes:
      - ./:/var/www/html

  #symfony
  symfony:
    build:
      context: docker-config
      dockerfile: symfony.dockerfile
    container_name: symfony_cli
    volumes:
      - ./:/var/www/html


  #mysql
  mysql:
    image: mysql:8.0
    container_name: mysql_epsivent
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE_SYMFONY}
      MYSQL_USER: ${MYSQL_USER_SYMFONY}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD_SYMFONY}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_SYMFONY}
    volumes:
      - ./docker-config/provision/mysql/init/:/docker-entrypoint-initdb.d
      - ./data/mysql/:/var/lib/mysql


  #GUI pour base de donnée
  #phpmyadmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_epsivent
    ports:
      - '8080:80'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_SYMFONY}
      PMA_HOST: mysql
      PMA_PORT: ${MYSQL_PORT}
    depends_on:
      - mysql

  #Keycloak
  keycloak:
    image: jboss/keycloak
    container_name: keycloak_epsivent
    environment:
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_DATABASE: ${MYSQL_DATABASE_KEYCLOAK}
      DB_USER: ${MYSQL_USER_KEYCLOAK}
      DB_PASSWORD: ${MYSQL_PASSWORD_KEYCLOAK}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      PROXY_ADDRESS_FORWARDING: 'true'
    ports:
      - "28080:8080"
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
