controllers:
    resource: ../../src/Festival/Infrastructure/Symfony5/Controller/
    type: annotation

kernel:
    resource: ../../src/Festival/Infrastructure/Symfony5/Kernel.php
    type: annotation
