controllers:
    resource: ../../src/FileManager/Infrastructure/Symfony5/Controller/
    type: annotation

kernel:
    resource: ../../src/FileManager/Infrastructure/Symfony5/Kernel.php
    type: annotation
