# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Symfony5\Doctrine\:
        resource: '../src/Festival/Infrastructure/Symfony5/Doctrine/'
        tags: ['festival.autowire']

    Symfony5\:
        resource: '../src/Festival/Infrastructure/Symfony5/'
        exclude: '../src/Festival/Infrastructure/Symfony5/{Doctrine,DependencyInjection,Kernel.php}'

    #    Symfony5\Twig\:
    #        resource: '../src/Festival/Infrastructure/Symfony5/Twig'
    #        tags: ['twig.extension']

    Festival\Domain\:
        resource: '../src/Festival/Domain/'
        exclude: '../src/Festival/Domain/{**/Entity,**/Error,**/Model}'

    Festival\Presentation\:
        resource: '../src/Festival/Presentation/'
        exclude: '../src/Festival/Presentation/{**/Entity,**/Error,**/Model}'

    Festival\SharedKernel\:
        resource: '../src/Festival/SharedKernel'

    Symfony5\Controller\:
        resource: '../src/Festival/Infrastructure/Symfony5/Controller/'
        tags: ['controller.service_arguments']


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
